### ISSUE TITLE
Started to fail on EKS 1.21 cluster after last version

### ISSUE THREAD

**Issue by bergerx** [bergerx/kubectl-status#331]
```
> status v0.7.2 -> v0.7.3
> ks node ip-10-0-0-64.eu-west-1.compute.internal
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

@ekesken ^

**Comment by bergerx** [comment]
https://github.com/aws/aws-cli/issues/6920 seems like a ridiculous history with no clear solution, many people suggested downgrading the client version to at least 1.23 or upgrading the awc-cli version to 2.6.3+ (I'm not sure either would really solve).

Unfortunately, this is not easy to address as [Kubernetes Version Skew Policy](https://kubernetes.io/releases/version-skew-policy/#kubectl) defines that they support only +/- 1 version. But there are Kubernetes versions from 1.20 to 1.25 out there, and here I have to support all that range with a single version as Krew also doesn't really provide a way to install different versions (see https://github.com/kubernetes-sigs/krew/issues/343)

@ekesken, is it possible to upgrade your azure cli? Or you can uninstall the krew plugin and download&install the binary release from https://github.com/bergerx/kubectl-status/releases/tag/v0.7.2

An alternative method could be to support installing the plugin without krew for such cases.

**Comment by bergerx** [comment]
Helm solved the issue by creating a supported version table for Kubernetes versions. And they have a corresponding MINOR version for each Kubernetes MINOR version: https://helm.sh/docs/topics/version_skew/#supported-version-skew

> When a new version of Helm is released, it is compiled against a particular minor version of Kubernetes. For example, Helm 3.0.0 interacts with Kubernetes using the Kubernetes 1.16.2 client, so it is compatible with Kubernetes 1.16.
>
> As of Helm 3, Helm is assumed to be compatible with n-3 versions of Kubernetes it was compiled against. Due to Kubernetes' changes between minor versions, Helm 2's support policy is slightly stricter, assuming to be compatible with n-1 versions of Kubernetes.

But, this issue still falls into a gray area as it seems to be caused by AWS' own client tooling rather than being a server/client skew policy.

And yet neither Helm (https://github.com/helm/helm/issues/10975#issuecomment-1132139799) nor others (https://github.com/hashicorp/terraform-provider-helm/issues/893, [Tanzu - Failure to connect to AWS EKS clusters](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.2/tap/GUID-troubleshooting-tap-troubleshoot-using-tap.html#failure-to-connect-to-aws-eks-clusters-14)) were able to avoid hitting this issue.

A good guideline to mitigate the issue seems to be documented here: [Tanzu - Failure to connect to AWS EKS clusters](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.2/tap/GUID-troubleshooting-tap-troubleshoot-using-tap.html#failure-to-connect-to-aws-eks-clusters-14)

**Comment by ekesken** [comment]
> @ekesken, is it possible to upgrade your azure cli? Or you can uninstall the krew plugin and download&install the binary release from https://github.com/bergerx/kubectl-status/releases/tag/v0.7.2

I tried with aws-cli/2.7.33, it didn't work, downgrading the plugin to 0.7.2 worked.
