### ISSUE TITLE
Reports incorrect relative times

### ISSUE THREAD

**Issue by jasonstitt** [bergerx/kubectl-status#38]
This is from `kubectl describe hpa` which is accurate:

```
  Normal  SuccessfulRescale  29m (x2 over 41m)  horizontal-pod-autoscaler  New size: 100; reason: external metric AWS-SQS-Queue-ApproximateNumberOfMessages-helloworld(&LabelSelector{MatchLabels:map[string]string{deploymentName: sqs-consumer,},MatchExpressions:[]LabelSelectorRequirement{},}) above target
```

This is from `kubectl status hpa`:

```
    SuccessfulRescale 4h ago (x2 over 4h) from horizontal-pod-autoscaler: New size: 100; reason: external metric AWS-SQS-Queue-ApproximateNumberOfMessages-helloworld(&LabelSelector{MatchLabels:map[string]string{deploymentName: sqs-consumer,},MatchExpressions:[]LabelSelectorRequirement{},}) above target
```

My local TZ offset is -0500, not sure if that's related or not.

Seeing the same with other object types (e.g. pod, hpa is just an example).

**Comment by bric3** [comment]
I noticed the same issue when getting status pods.

For example in a pod description, the start time is `Wed, 17 Jun 2020 17:15:46 +0200`, but reading the status report it has been started 11 hours ago, while in reality it was 9h ago.

I also suspect the timezone to have a role in this.

```
date +"%Y-%m-%dT%H:%M:%S%z"
2020-06-18T02:32:16+0200
```

**Comment by bergerx** [comment]
Oh hey, nice to see others using the plugin, I also hit the issue recently but didn't care about fixing it thinking i'm the only one using it :)

The issue is about TZ handling in the code, here is the workaround, i'll try to fix and release a new version shortly:

```
TZ=UTC kubectl status ...
```

**Comment by 037g** [comment]
I'm also experiencing this.
